import {
  RiAccountCircleFill,
  RiArrowDropLeftLine,
  RiBookmarkLine,
  RiBookmarkFill,
  RiCake2Line,
  RiChat1Line,
  RiChat1Fill,
  RiEyeFill,
  RiEyeOffFill,
  RiFileList3Line,
  RiGithubFill,
  RiGoogleFill,
  RiHeartAddFill,
  RiHeartAddLine,
  RiLock2Fill,
  RiLogoutCircleRLine,
  RiMailFill,
  RiMailLine,
  RiMoreFill,
  RiSearch2Line,
  RiSettingsLine,
  RiCloseLine,
} from "react-icons/ri";

const icons = {
  RiSearch2Line,
  RiGoogleFill,
  RiGithubFill,
  RiMailFill,
  RiLock2Fill,
  RiEyeFill,
  RiEyeOffFill,
  RiBookmarkLine,
  RiBookmarkFill,
  RiHeartAddLine,
  RiChat1Line,
  RiAccountCircleFill,
  RiCake2Line,
  RiMailLine,
  RiSettingsLine,
  RiFileList3Line,
  RiArrowDropLeftLine,
  RiLogoutCircleRLine,
  RiMoreFill,
  RiHeartAddFill,
  RiCloseLine,
  RiChat1Fill,
};

export default icons;
